test:
	java main ../tests/double_input.txt	
	java main ../tests/double_funcall_with_int_casting.txt
	java main ../tests/double_casting_addition.txt
	java main ../tests/givenDoubleToReturnForIntFuction_returnTypeIsNotCorrect.txt
	java main ../tests/double_casting_addition.txt
	java main ../tests/interpreter_input.txt
	
