import org.antlr.v4.runtime.tree.ParseTreeVisitor;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import org.antlr.v4.runtime.CharStreams;
import java.util.*;
import java.io.IOException;

public class main {
    public static void main(String[] args) throws IOException{

	// we expect exactly one argument: the name of the input file
	if (args.length!=1) {
	    System.err.println("\n");
	    System.err.println("Simple calculator\n");
	    System.err.println("=================\n\n");
	    System.err.println("Please give as input argument a filename\n");
	    System.exit(-1);
	}
	String filename=args[0];

	// open the input file
	CharStream input = CharStreams.fromFileName(filename);
	    //new ANTLRFileStream (filename); // depricated
	
	// create a lexer/scanner
	simpleCalcLexer lex = new simpleCalcLexer(input);
	
	// get the stream of tokens from the scanner
	CommonTokenStream tokens = new CommonTokenStream(lex);
	
	// create a parser
	simpleCalcParser parser = new simpleCalcParser(tokens);
	
	// and parse anything from the grammar for "start"
	ParseTree parseTree = parser.start();

	// Construct an interpreter and run it on the parse tree
	Interpreter interpreter = new Interpreter();
	AST result=interpreter.visit(parseTree);
	
	System.out.println("The result is: "+result.eval(new Environment()));
    }
}



// We write an interpreter that implements interface
// "simpleCalcVisitor<T>" that is automatically generated by ANTLR
// This is parameterized over a return type "<T>" which is in our case
// simply a Double.

class Interpreter extends AbstractParseTreeVisitor<AST> implements simpleCalcVisitor<AST> {

    public AST visitStart(simpleCalcParser.StartContext ctx){
	List<Assign> as=new ArrayList<Assign>();
	
	for (simpleCalcParser.AssignContext a:ctx.as)
	    as.add((Assign) visit(a)); 

	return new Start(as,(Expr) visit(ctx.e));
    };

    public AST visitParenthesis(simpleCalcParser.ParenthesisContext ctx){
	return visit(ctx.e);
    };
    
    public AST visitVariable(simpleCalcParser.VariableContext ctx){
	String varname=ctx.x.getText();
	return new Variable(varname);
    };
    
    public AST visitAddition(simpleCalcParser.AdditionContext ctx){
	Expr e1=(Expr)visit(ctx.e1);
	Expr e2=(Expr)visit(ctx.e2);
	
	if (ctx.op.getText().equals("+"))
	    return new Addition(e1,e2);
	else
	    return new Subtraction(e1,e2);
    };

    public AST visitMultiplication(simpleCalcParser.MultiplicationContext ctx){
	Expr e1=(Expr)visit(ctx.e1);
	Expr e2=(Expr)visit(ctx.e2);
	
	return new Multiplication(e1,e2);
    };

    public AST visitDivision(simpleCalcParser.DivisionContext ctx){
        Expr e1 = (Expr) visit(ctx.e1); // can be new Addition, Constant etc.
        Expr e2 = (Expr) visit(ctx.e2);
        return new Division(e1,e2);
    }

    public AST visitConstant(simpleCalcParser.ConstantContext ctx){
	return new Constant(Double.parseDouble(ctx.c.getText())); 
    };

    public AST visitSignedConstant(simpleCalcParser.SignedConstantContext ctx){
	return new Constant(Double.parseDouble(ctx.getText()));
    };
    
    public AST visitAssign(simpleCalcParser.AssignContext ctx){
	
	// New implementation: evaluate the expression and store it in the environment for the given
	// variable name
	String varname=ctx.x.getText();
	Expr e=(Expr)visit(ctx.e);

	return new Assign(varname,e);
    };

}

