test: 
	java main ../tests/if_false_expect_6.txt
	java main ../tests/if_true_expect_4.txt
	java main ../tests/if_one_stat_false_expected_2.txt
	java main ../tests/if_one_stat_true_expect_1.txt
	java main ../tests/if_const_true_expect_2.txt
	java main ../tests/if_const_false_expect_3.txt
