test: 
	java main ../tests/if_false_expect_6.txt
	java main ../tests/if_true_expect_4.txt
	java main ../tests/if_one_stat_false_expected_2.txt
	java main ../tests/if_one_stat_true_expect_1.txt
	java main ../tests/if_const_true_expect_2.txt
	java main ../tests/if_const_false_expect_3.txt
	java main ../tests/if_and_true_expect_2.txt
	java main ../tests/if_OR_true_expect_2.txt
	java main ../tests/if_OR_false_expect_0.txt
	java main ../tests/if_paranthesis_expected_1.txt
	java main ../tests/while_expect_5.txt
	java main ../tests/if_not_except_1.txt
	java main ../tests/if_NOT_AND_expect1.txt
	java main ../tests/if_notequals_expect_1.txt
	java main ../tests/arithmetic_exp_3.txt
	java main ../tests/increment_expect_2.txt
